#!/bin/bash

## License: WTFPL2 http://wtfpl2.com/
## copyleft uzver(at)protonmail.ch (ɔ) 2017
## https://notabug.org/uzver/myoutube

######## CONFIG ########
## Set prefered languages (subtitles and audio stream)
lang='ru,uk,en,us'

## Set executables:
mplayerexec="mplayer"
mpvexec="mpv"
# vlcexec="vlc"
vlcexec="cvlc"
ffplayexec="ffplay"
#ffmpegexec="ffmpeg"
ffmpegexec="/usr/bin/ffmpeg"
# ffplayexec="avplay"
# ffmpegexec="avconv"
#youtubedlexec="youtube-dl"
#youtubedlexec="/usr/bin/youtube-dl" # apt
#youtubedlexec="/usr/local/bin/youtube-dl" # pip
youtubedlexec="/usr/local/bin/yt-dlp" # yt-dlp pip

verbose=0

## Use or not the XVideo extention XFree86 4.x for hardware acceleration.
## If you can't use special driver for your video card (for graphic acceleration), then choosing this may be the best solution
#xvout=1

## Some cpu optimization
optimization=1
## cpu cores to utilize
cores=$(grep -c processor /proc/cpuinfo)

## Video frame size
width=""
height=""
geometry=""

## Set cookies file:
cookies_file="$(mktemp -u /tmp/myoutube-cookies.XXXXXX)"

## Set useragent:
#user_agent='Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20100101 Firefox/6.0' 
#user_agent='Android' # Fails with youtube-dl for some reason

## Set default format:
##  First match will be played.
##  By default get 22 format (youtube),
##   if not found then get the best of mp4 (youtube),
##   if not found then get the best (all).
##  Note that by default for not audio format dash formats disabled,
##   you can enable them by setting `skipdash=0' ↓.

##  youtube/vimeo/vk/vk/ok/all/all
hdformat='22/136+140/http-720p/url720/cache720/mpd-5/mpd-4/mp4/best'
##  youtube/vimeo/vk/vk/facebook/dailymotion/ok/ok/all
sdformat='18/43/35/5/http-360p/url360/cache360/progressive_sd_src_no_ratelimit/http-380/mpd-3/mpd-4/mp4/best'
ldformat='35/5/36/18/43/http-360p/url360/cache360/progressive_sd_src_no_ratelimit/http-240/http-380/mpd-2/mpd-1/mp4/best'
##  yt/yt/yt/yt/yt/yt/yt/yt/vimeo/vk/vk/facebook/dailymotion/ok/ok/all
aformat='141/251/140/171/18/43/35/5/36/http-360p/url360/cache360/progressive_sd_src_no_ratelimit/http-380/mpd-3/mpd-2/mp4/best' # dash audio
format="$hdformat"

## Set audio only
audioonly=0 # 1: audio only, 0: audio & video 

## Set use of dash formats (youtube):
skipdash=1 # 1: skip dash formats, 0: use dash formats.


## Player options:
mpvopts=("--quiet" "--msg-level=all=fatal" ${cookies_file:+"--cookies" "--cookies-file=\"$cookies_file\""} ${user_agent:+"--user-agent=\"$user_agent\""} "--cache=yes" ${lang:+"--alang=$lang" "--slang=$lang"} "--framedrop=decoder" "--stop-screensaver" "--ytdl" "--ytdl-raw-options=${cookies_file:+cookies=\"$cookies_file\",}${user_agent:+user-agent=\"$user_agent\",}youtube-skip-dash-manifest=") # mpv 0.7+
ffplayopts=("-v" "error" "-framedrop") # "-autoexit"
vlcopts=("--quiet" "--play-and-exit" "--no-video-title-show" ${lang:+"--audio-language" "$lang" "--sub-language" "$lang"})
mplayeropts=("-quiet" "-msglevel" "all=1" "-prefer-ipv4" ${cookies_file:+"-cookies" "-cookies-file" "\"$cookies_file\""} ${user_agent:+"-user-agent" "\"$user_agent\""} "-cache" "30000" "-cache-min" "5" ${lang:+"-alang" "$lang" "-slang" "$lang"} "-framedrop")
########################

player=("$mplayerexec" "${mplayeropts[@]}")

exec="$(basename "$0")"; [[ "$exec" ]] || exec="${0##*/}"

printhelp() {
cat <<EOF
Watch video directly in desktop player via youtube-dl... or local file.
For now players available: mplayer, mpv, ffplay/avplay, vlc

$exec [OPTIONS [-f FORMAT] [PLAYER] [PLAYER OPTIONS]] <URL|FILE>
The order of passed options has matter!

See also ######## CONFIG ######## section of this script.

OPTIONS:
    -h, --help      - print this help.
    -v              - vernose.

  FORMAT:
    -f FORMAT       - accepts: 'h', 's', 'l', 'a' or youtube-dl formats;
                      'h' is hd (high) quality: first try to get 1280x720,
                       if not then best mp4, then the best (defaut);
                      's' is sd (standart) quality: first try to get 640x360,
                       then lower, then the best;
                      'l' is low quality: first try to get 480x240,
                       then lower, then 's', then the best;
                      'a' is audio only: first try to get youtube dash audio,
                       if not then 's', 'l', best video & output only sound
                      (see: youtube-dl -F <URL>).

  PLAYER:
    By default watch in mplayer.
    -mp             - watch in mpv.
    -ff             - watch in ffplay.
    -vl             - watch in vlc.

   PLAYER OPTIONS:
    MPLAYER:
      Script accepts all mplayer options.
      e.g.:         -fs -really-quiet -vo fbdev2 -framedrop -zoom -xy 1024 -subcp enca:ru:UTF-8 -nodouble -dr -lavdopts skiploopfilter=all:threads=2 ...
    MPV:
      Script accepts all mpv options if -mp optiion has been passed before.
      e.g.:         --msg-level=all=no --really-quiet --no-terminal --vo=null --no-video --sub-codepage=enca:ru:UTF-8 --vd-lavc-skiploopfilter=all --vd-lavc-threads=2
                    --framedrop=decoder --no-terminal --heartbeat-interval=240
                    --heartbeat-cmd="xscreensaver-command -deactivate"
                    --heartbeat-cmd="gnome-screensaver-command -p" ...
    FFPLAY:
      Script accepts all ffplay options if -ff optiion has been passed before.
      e.g.:         -fs -vn -nodisp -framedrop -fast -x 1024 -y 768 ...
    VLC:
      Script accepts all ffplay options if -vl optiion has been passed before.
      e.g.:         --fullscreen ...

EXAMPLES:
    MPLAYER:
        $exec "http://youtu.be/MejbOFk7H6c"
      Get quality 360p and play fullscreen:
        $exec -f s -fs "http://youtu.be/MejbOFk7H6c"
      Get audio dash format (youtube):
        $exec -f a "http://youtu.be/MejbOFk7H6c"
		$exec -f a "http://tunein.com/station/?StationId=141430"

    MPV:
        $exec -mp "http://youtu.be/MejbOFk7H6c"
      Get best format and play fullscreen:
        $exec -f best -mp --force-window --really-quiet --fs --heartbeat-cmd="gnome-screensaver-command -p" "http://youtu.be/MejbOFk7H6c"
      Get audio dash format (youtube):
        $exec -f a -mp "http://youtu.be/MejbOFk7H6c"
        $exec -f a -mp --vid=no "http://youtu.be/MejbOFk7H6c"
        $exec -f a -mp --vid=no "http://tunein.com/station/?StationId=141430"

    FFPLAY:
        $exec -ff "http://youtu.be/MejbOFk7H6c"
      Get audio dash format (youtube):
        $exec -f a -ff "http://youtu.be/MejbOFk7H6c"
        $exec -f a -ff -vn -showmode 1 -x 400 -y 100 "http://youtu.be/MejbOFk7H6c"
		$exec -f a -ff -vn -showmode 1 -x 400 -y 100 "http://tunein.com/station/?StationId=141430"

    VLC:
        $exec -vl "http://youtu.be/MejbOFk7H6c"
      Get low quality format and play fullscreen:
        $exec -f l -vl -f "http://youtu.be/MejbOFk7H6c"
      Get audio dash format (youtube):
        $exec -f a -vl "http://youtu.be/MejbOFk7H6c"
        $exec -f a -vl --no-video --audio-visual=visual "http://youtu.be/MejbOFk7H6c"
		$exec -f a -vl --no-video --audio-visual=visual "http://tunein.com/station/?StationId=141430"

    VERBOSE:
        $exec -v -f h -mp "http://youtu.be/MejbOFk7H6c"
EOF
}

if [[ "$#" -lt "1" ]]; then
    printhelp
    exit 1
elif [[ "$1" == '-h' || "$1" == '-?' || "$1" == '--help' ]]; then
    printhelp
    exit 0
fi

if [[ "$1" == "-v" ]]; then verbose=1; shift; fi
if [[ "$1" == "-f" ]]; then
    if [[ "$2" && "$3" ]]; then
        format="$2"
        case "$format" in
            h) format="$hdformat" ;;
            s) format="$sdformat" ;;
            l) format="$ldformat" ;;
            a) format="$aformat"; skipdash=0; audioonly=1 ;;
            *) skipdash=0 ;;
        esac
    fi
    shift 2
    (($verbose)) && echo "getting format: $format"
fi


## Store all arguments in a bash array:
array=("$@")
## Find out length of an array:
len="${#array[@]}"
## Get the last argument (the last one is url):
_last="${array[$len-1]}"
## Extract and store all arguments before last:
args_="${array[@]:0:$len-1}"
## Unescape last argument
if [[ ! "$_last" =~ ^file:// ]]; then
    perl -v >& /dev/null
	hasperl=$?
    if ! (($hasperl == 127)); then
        _last="$(perl -MURI::Escape -e 'print uri_unescape($ARGV[0]);' "$_last")"
    else
		pver="$(python --version 2>&1)"
		pver="$(echo "${pver//Python/}"|cut -d'.' -f1)"
		if (("$pver" == 2)); then
			_last=$(python -c 'import sys,urllib; print urllib.unquote(sys.argv[1]).decode("utf8")' "$_last")
		elif [[ "$pver" -ge 3 ]]; then
			_last=$(python -c 'import sys; from urllib import parse; print(parse.unquote(sys.argv[1]))' "$_last")
		else
			echo '[error]: We need perl or python.'
			exit 1
		fi
	fi

    ## Can eat url:
    # https://m.youtube.com/watch?v=MejbOFk7H6c
    # https://www.youtube.com/watch?v=MejbOFk7H6c
    # youtube.com/watch?v=MejbOFk7H6c
    # http://youtu.be/MejbOFk7H6c
    # youtu.be/MejbOFk7H6c
    # MejbOFk7H6c
    # https://vk.com/away.php?to=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMejbOFk7H6c
    # https://youtube.com/v/MejbOFk7H6c?version=3
    # youtube.com/v/MejbOFk7H6c?version=3
    # https://youtube.com/embed/MejbOFk7H6c
    # youtube.com/embed/MejbOFk7H6c
    ## Here we'l got yid = youtube id or nothnig:
    yid="$(exps=('.*youtu\.be/\([^\/&?#]\+\)' '.*youtu.\+v[=/]\([^\/&?#]\+\)' '.*youtu.\+embed/\([^\/&?#]\+\)' '\([a-zA-Z0-9_-]\{11\}\)'); for exp in ${exps[@]}; do expr "$_last" : "$exp"; done)"
    ##  Get first non empty line, if exist get last argument
    #[[ "$yid" ]] && yid="$(echo $yid)" || yid="$_last"
    yid="$(echo $yid)"

    if [[ "$yid" ]]; then ## Youtube url or id was passed
        vidurl="https://www.youtube.com/watch?v=$yid"
    else ## Not youtube url or id was passed
        vidurl="$_last"
    fi
else
    localfile=1
    vidurl="$_last"
    url="$vidurl"
fi
#echo vidurl="$vidurl" url="$url"; exit
echo vidurl="$vidurl" url="$url"
## Escape file://
if [[ ! "$vidurl" =~ ^https?:/ ]]; then
    #echo 1if; exit
    if ! (($localfile)); then
        if ! [[ "$player" =~ ^mplayer ]]; then
            if ! (($hasperl == 127)); then
                # url=file://"$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$vidurl" | sed 's/%2F/\//g')"
                url=file://"$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$vidurl" | perl -pe 's|%2F|/|g')"
            else
                if (("$pver" == 2)); then
                    url=file://"$(python -c 'import sys,urllib; print urllib.quote(sys.argv[1]).decode("utf8")' "$vidurl")"
                elif [[ "$pver" -ge 3 ]]; then
                    url=file://"$(python -c 'import sys; from urllib import parse; print(parse.quote(sys.argv[1]))' "$vidurl")"
                else
                    #url=file://"$(echo "$vidurl" | sed 's/ /%20/g')"
                    url=file://"${vidurl// /%20}"
                fi
            fi
        else
            url=file://"$vidurl"
        fi
    fi
# FIXME: mpv ytdl extractor '.' bug: + && [[ "$yid" ]]
#elif [[ "$1" == '-mp' ]] && [[ "$yid" ]]; then
elif [[ "$1" == '-mp' ]]; then
    #echo 2if; exit
    url="$vidurl"
else ##  otherwise pass url to youtube-dl
    (($verbose)) && echo exec: "$youtubedlexec" --ignore-errors $([[ "$ffmpegexec" ]] && echo --prefer-ffmpeg --ffmpeg-location "$ffmpegexec") $((($skipdash)) && echo --youtube-skip-dash-manifest) --cookies="$cookies_file" --user-agent="$user_agent" -g $([[ "$format" ]] && echo "-f $format") "$vidurl"
    hotlink="$("$youtubedlexec" --ignore-errors $([[ "$ffmpegexec" ]] && echo --prefer-ffmpeg --ffmpeg-location "$ffmpegexec") $((($skipdash)) && echo --youtube-skip-dash-manifest) --cookies="$cookies_file" --user-agent="$user_agent" -g $([[ "$format" ]] && echo "-f $format") "$vidurl")"
    url="$hotlink"
fi
#echo yid="$yid" vidurl="$vidurl" url="$url" hotlink="$hotlink"; exit
case "$1" in
    ## Watch in mpv:
    -mp)
        _args_="${array[@]:1:$len-2}"
        mpvopts+=("--ytdl-format=$format")
        player=("$mpvexec" "${mpvopts[@]}")
        (($xvout)) && player+=("--vo=xv")
        (($optimization)) && player+=("--vd-lavc-threads=$cores" "--vd-lavc-skiploopfilter=all" )
        (($width)) && player+=("-geometry=$width")
        (($height)) && player+=("")
        [[ "$geometry" ]] && player+=("--geometry" "$geometry")
        (($audioonly)) && player+=("--no-video")
        [[ "$lang" ]] && player+=("--sub-codepage=enca:${lang%%,*}:UTF-8")
        (($verbose)) && player+=("--msg-level=all=status")
        [[ -n "$_args_" && ! "$len" = 2 ]] && for i in "${_args_[@]}"; do player+=($i); done
    ;;
    ## Watch in ffplay:
    -ff)
        # if ! expr "$ffplayexec" : 'avplay' > /dev/null; then
        if ! [[ "$ffplayexec" =~ avplay ]]; then
            # ffplay -version >& /dev/null
            which ffplay >& /dev/null
            if (($? == 1)); then
                ffplayexec="avplay"
                ffmpegexec="avconv"
            fi
        fi
        (($xvout)) && export VIDEODEV=xv
        player=("$ffplayexec" "${ffplayopts[@]}")
        #TODO: (($optimization)) && player+=("")
        (($width)) && player+=("-x" "$width")
        (($height)) && player+=("-y" "$height")
        [[ "$geometry" ]] && player+=("-s" "$geometry" "-video_size" "$geometry")
        (($audioonly)) && player+=("-vn" "-showmode" "1" "-x" "400" "-y" "100")
        #TODO: [[ "$lang" ]] && player+=("")
        (($verbose)) && player+=("-v" "info")
        _args_="${array[@]:1:$len-2}"
        [[ -n "$_args_" && ! "$len" = 2 ]] && for i in "${_args_[@]}"; do player+=($i); done
    ;;
    ## Watch in vlc:
    -vl)
        _args_="${array[@]:1:$len-2}"
        player=("$vlcexec" "${vlcopts[@]}")
        (($xvout)) && player+=("--vout=xcb_xv")
        (($optimization)) && player+=("")
        (($width)) && player+=("")
        (($height)) && player+=("")
        [[ "$geometry" ]] && player+=("")
        (($audioonly)) && player+=("--intf" "dummy" "--novideo")
        [[ "$lang" ]] && player+=("")
        (($verbose)) && player+=("--no-quiet")
        [[ -n "$_args_" && ! "$len" = 2 ]] && for i in "${_args_[@]}"; do player+=($i); done
    ;;
    ## Watch in mplayer:
    *)
        player=("$mplayerexec" "${mplayeropts[@]}")
        (($xvout)) && player+=("-vo" "xv")
        (($optimization)) && player+=("-lavdopts" "skiploopfilter=all:threads=$cores" "-nodouble" "-dr")
        (($width)) && player+=("-xy" "1024" "-zoom")
        (($height)) && player+=("-y" "$height")
        [[ "$geometry" ]] && player+=("")
        (($audioonly)) && player+=("-novideo")
        [[ "$lang" ]] && player+=("-subcp" "enca:${lang%%,*}:UTF-8")
        (($verbose)) && player+=("-msglevel" "all=5")
        [[ -n "$args_" && ! "$len" = 2 ]] && player+=("$args_")
    ;;
esac

## Play now
(($verbose)) && echo "exec: ${player[@]} $url"
"${player[@]}" "$url"
(($?)) && fail=$? && failmsg+="\nmyoutube \e[0;31mFail!\e[m"

## Delete cookies file
if [[ -f "$cookies_file" ]]; then /bin/rm "$cookies_file"; fi

if (($fail)); then
    # notify-send -u critical -t 3000 -i error "myoutube" "Failed!" &
    (($verbose)) && echo -e "$failmsg"
    exit $fail
else
    exit 0
fi

## TODO:
# >&2
